In [1]:
import pandas as pd
import sys
from pathlib import Path

project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

print("Project root:", project_root)
print("src exists:", (project_root / "src").exists())

Project root: c:\University\Year4\Thesis\AML-Thesis
src exists: True

**For google collab**
---

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import sys

project_root = Path("/content/drive/MyDrive/Thesis/AML-Thesis")

if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Move into project directory
%cd $project_root

# Verify structure
print("Project root:", project_root)
print("src exists:", (project_root / "src").exists())
print("data exists:", (project_root / "data").exists())
print("requirements exists:", (project_root / "requirements.txt").exists())

# Install dependencies
!pip install -r requirements.txt

In [ ]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

---

In [2]:
from src.data_loader import load_transactions_graph_baseline_simple

X_train, X_test, y_train, y_test, train_time, test_time = load_transactions_graph_baseline_simple()

assert "Time step" not in X_train.columns
assert "Time step" not in X_test.columns
assert len(test_time) == len(y_test) == len(X_test)
assert len(train_time) == len(y_train) == len(X_train)
assert max(train_time) < min(test_time), "Time boundary not clean!"

print(f"Train steps: {sorted(train_time.unique())[0]}–{sorted(train_time.unique())[-1]} ({len(train_time)} rows)")
print(f"Test steps:  {sorted(test_time.unique())[0]}–{sorted(test_time.unique())[-1]} ({len(test_time)} rows)")
print(f"Illicit rate — train: {y_train.mean():.4f}, test: {y_test.mean():.4f}")

Train steps: 1–39 (34971 rows)
Test steps:  40–49 (11074 rows)
Illicit rate — train: 0.1118, test: 0.0574

In [3]:
from src.data_loader import _load_raw_elliptic_transactions_combined

trn_combined = _load_raw_elliptic_transactions_combined()
trn_combined

,txId,Time step,Local_feature_1,Local_feature_2,Local_feature_3,Local_feature_4,Local_feature_5,Local_feature_6,Local_feature_7,Local_feature_8,...,in_BTC_max,in_BTC_mean,in_BTC_median,in_BTC_total,out_BTC_min,out_BTC_max,out_BTC_mean,out_BTC_median,out_BTC_total,class
0,3321,1,-0.169615,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160199,...,0.534072,0.534072,0.534072,0.534072,1.668990e-01,0.367074,0.266986,0.266986,0.533972,3
1,11108,1,-0.137586,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.127429,...,5.611878,5.611878,5.611878,5.611878,5.861940e-01,5.025584,2.805889,2.805889,5.611778,3
2,51816,1,-0.170103,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160699,...,0.456608,0.456608,0.456608,0.456608,2.279902e-01,0.228518,0.228254,0.228254,0.456508,3
3,68869,1,-0.114267,-0.184668,-1.201369,0.028105,-0.043875,-0.113002,0.547008,-0.161652,...,8.000000,3.102967,1.000000,9.308900,1.229000e+00,8.079800,4.654400,4.654400,9.308800,2
4,89273,1,5.202107,-0.210553,-1.756361,-0.121970,260.090707,-0.113002,-0.061584,5.335864,...,852.164680,852.164680,852.164680,852.164680,1.300000e-07,41.264036,0.065016,0.000441,852.164680,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203764,158304003,49,-0.165622,-0.139563,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.156113,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
203765,158303998,49,-0.167040,-0.139563,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.157564,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
203766,158303966,49,-0.167040,-0.139563,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.157564,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
203767,161526077,49,-0.172212,-0.139573,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.162856,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
203768,194103537,49,-0.172212,-0.139573,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.162856,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3

In [4]:
from src.data_loader import _load_preprocessed_elliptic_graph

trn_graph_cleaned = _load_preprocessed_elliptic_graph()
trn_graph_cleaned

,txId,Time step,Local_feature_1,Local_feature_2,Local_feature_3,Local_feature_4,Local_feature_5,Local_feature_6,Local_feature_7,Local_feature_8,...,in_BTC_max,in_BTC_mean,in_BTC_median,in_BTC_total,out_BTC_min,out_BTC_max,out_BTC_mean,out_BTC_median,out_BTC_total,class
0,3321,1,-0.169615,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160199,...,0.534072,0.534072,0.534072,0.534072,1.668990e-01,0.367074,0.266986,0.266986,0.533972,3
1,11108,1,-0.137586,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.127429,...,5.611878,5.611878,5.611878,5.611878,5.861940e-01,5.025584,2.805889,2.805889,5.611778,3
2,51816,1,-0.170103,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.160699,...,0.456608,0.456608,0.456608,0.456608,2.279902e-01,0.228518,0.228254,0.228254,0.456508,3
3,68869,1,-0.114267,-0.184668,-1.201369,0.028105,-0.043875,-0.113002,0.547008,-0.161652,...,8.000000,3.102967,1.000000,9.308900,1.229000e+00,8.079800,4.654400,4.654400,9.308800,0
4,89273,1,5.202107,-0.210553,-1.756361,-0.121970,260.090707,-0.113002,-0.061584,5.335864,...,852.164680,852.164680,852.164680,852.164680,1.300000e-07,41.264036,0.065016,0.000441,852.164680,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202799,194747812,49,0.558398,-0.198956,-0.091383,-0.121970,-0.043875,-0.113002,-0.061584,0.584665,...,115.952889,115.952889,115.952889,115.952889,1.653300e+00,114.299544,57.976422,57.976422,115.952844,3
202800,194747925,49,0.547658,-0.198956,-0.091383,-0.121970,-0.043875,-0.113002,-0.061584,0.573676,...,114.250098,114.250098,114.250098,114.250098,2.035300e-02,114.229700,57.125027,57.125027,114.250053,3
202801,194748063,49,0.543600,-0.198853,-0.091383,-0.121970,-0.043875,-0.113002,-0.061584,0.569524,...,113.606771,113.606771,113.606771,113.606771,9.257490e-01,112.680977,56.803363,56.803363,113.606726,3
202802,194748070,49,0.537760,-0.198853,-0.091383,-0.121970,-0.043875,-0.113002,-0.061584,0.563549,...,112.680977,112.680977,112.680977,112.680977,3.026970e-01,112.378235,56.340466,56.340466,112.680932,3
202803,194835939,49,-0.170463,-0.152788,1.018602,-0.121970,-0.063725,-0.113002,-0.061584,-0.161066,...,0.399769,0.399769,0.399769,0.399769,3.995460e-01,0.399546,0.399546,0.399546,0.399546,3

In [5]:
trn_graph_cleaned.isna().sum()

txId               0
Time step          0
Local_feature_1    0
Local_feature_2    0
Local_feature_3    0
                  ..
out_BTC_max        0
out_BTC_mean       0
out_BTC_median     0
out_BTC_total      0
class              0
Length: 185, dtype: int64

In [6]:
print((trn_graph_cleaned["class"] == 3).any())

True

In [7]:
print((trn_graph_cleaned["class"] == 2).any())

False

In [8]:
print(trn_graph_cleaned.duplicated().sum())

0

In [9]:
from src.training import _evaluate_per_timestep

time_steps = pd.Series([40, 40, 40, 41, 41, 41])
y_test     = pd.Series([1, 0, 1, 0, 1, 0])
y_pred     = pd.Series([1, 0, 0, 0, 1, 1])
y_proba    = pd.Series([0.9, 0.1, 0.4, 0.2, 0.8, 0.6])

print(_evaluate_per_timestep(time_steps, y_test, y_pred, y_proba))

   time_step  n_samples  n_positives  precision  recall        f1  roc_auc
0         40          3            2        1.0     0.5  0.666667      1.0
1         41          3            1        0.5     1.0  0.666667      1.0

In [10]:
from src.training import run_random_forest_graph_experiments

rf_agg, rf_per_ts = run_random_forest_graph_experiments()
print(rf_agg)

                       dataset          model            setup  accuracy  \
0  elliptic-transactions-graph  Random Forest           simple  0.974986
1  elliptic-transactions-graph  Random Forest  simple_balanced  0.973361

   precision    recall        f1   roc_auc
0   0.973615  0.580189  0.727094  0.924149
1   0.974930  0.550314  0.703518  0.933417

In [11]:
rf_agg

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-transactions-graph,Random Forest,simple,0.974986,0.973615,0.580189,0.727094,0.924149
1,elliptic-transactions-graph,Random Forest,simple_balanced,0.973361,0.974930,0.550314,0.703518,0.933417

In [12]:
print(rf_per_ts["simple_balanced"])

   time_step  n_samples  n_positives  precision    recall        f1   roc_auc
0         40       1208          112   1.000000  0.598214  0.748603  0.907708
1         41       1127          116   1.000000  0.887931  0.940639  0.981420
2         42       2142          239   0.994382  0.740586  0.848921  0.966694
3         43       1327           24   0.000000  0.000000  0.000000  0.648903
4         44       1578           24   0.166667  0.041667  0.066667  0.834808
5         45       1198            5   0.000000  0.000000  0.000000  0.808131
6         46        711            2   1.000000  0.500000  0.666667  0.977080
7         47        836           22   0.000000  0.000000  0.000000  0.893065
8         48        471           36   0.000000  0.000000  0.000000  0.925415
9         49        476           56   1.000000  0.017857  0.035088  0.931781

In [13]:
rf_per_ts["simple"]

   time_step  n_samples  n_positives  precision    recall        f1   roc_auc
0         40       1208          112   1.000000  0.616071  0.762431  0.906898
1         41       1127          116   1.000000  0.922414  0.959641  0.986864
2         42       2142          239   0.994764  0.794979  0.883721  0.962822
3         43       1327           24   0.000000  0.000000  0.000000  0.642684
4         44       1578           24   0.166667  0.041667  0.066667  0.819297
5         45       1198            5   0.000000  0.000000  0.000000  0.781727
6         46        711            2   0.500000  0.500000  0.500000  0.955924
7         47        836           22   0.000000  0.000000  0.000000  0.835883
8         48        471           36   0.000000  0.000000  0.000000  0.894987
9         49        476           56   1.000000  0.017857  0.035088  0.925510

In [14]:
from IPython.display import display
from src.training import run_xgboost_graph_experiments
from src.training import run_lightgbm_graph_experiments

rf_agg,   rf_per_ts   = run_random_forest_graph_experiments()
xgb_agg,  xgb_per_ts  = run_xgboost_graph_experiments()
lgbm_agg, lgbm_per_ts = run_lightgbm_graph_experiments()

graph_baseline_agg = pd.concat([rf_agg, xgb_agg, lgbm_agg], ignore_index=True)

c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [21:14:01] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
c:\University\Year4\Thesis\AML-Thesis\.venv\Lib\site-packages\xgboost\training.py:200: UserWarning: [21:14:10] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

[LightGBM] [Info] Number of positive: 3909, number of negative: 31062
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.013900 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 42427
[LightGBM] [Info] Number of data points in the train set: 34971, number of used features: 182
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.111778 -> initscore=-2.072704
[LightGBM] [Info] Start training from score -2.072704
[LightGBM] [Info] Number of positive: 3909, number of negative: 31062
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.017086 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 42427
[LightGBM] [Info] Number of data points in the train set: 34971, number of used features: 182
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=-0.000000
[LightGBM] [Info] Start training from score -0.000000

In [15]:
graph_baseline_agg

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-transactions-graph,Random Forest,simple,0.974986,0.973615,0.580189,0.727094,0.924149
1,elliptic-transactions-graph,Random Forest,simple_balanced,0.973361,0.974930,0.550314,0.703518,0.933417
2,elliptic-transactions-graph,XGBoost,simple,0.975077,0.959184,0.591195,0.731518,0.947289
3,elliptic-transactions-graph,XGBoost,simple_balanced,0.974083,0.872068,0.643082,0.740271,0.953025
4,elliptic-transactions-graph,LightGBM,simple,0.975257,0.957071,0.595912,0.734496,0.952727
5,elliptic-transactions-graph,LightGBM,simple_balanced,0.976341,0.932870,0.633648,0.754682,0.950692

In [16]:
print("Random Forest — simple")
display(rf_per_ts["simple"])

print("XGBoost — simple")
display(xgb_per_ts["simple"])

print("LightGBM — simple")
display(lgbm_per_ts["simple"])

Random Forest — simple

   time_step  n_samples  n_positives  precision    recall        f1   roc_auc
0         40       1208          112   1.000000  0.616071  0.762431  0.906898
1         41       1127          116   1.000000  0.922414  0.959641  0.986864
2         42       2142          239   0.994764  0.794979  0.883721  0.962822
3         43       1327           24   0.000000  0.000000  0.000000  0.642684
4         44       1578           24   0.166667  0.041667  0.066667  0.819297
5         45       1198            5   0.000000  0.000000  0.000000  0.781727
6         46        711            2   0.500000  0.500000  0.500000  0.955924
7         47        836           22   0.000000  0.000000  0.000000  0.835883
8         48        471           36   0.000000  0.000000  0.000000  0.894987
9         49        476           56   1.000000  0.017857  0.035088  0.925510

XGBoost — simple

   time_step  n_samples  n_positives  precision    recall        f1   roc_auc
0         40       1208          112   0.986301  0.642857  0.778378  0.928694
1         41       1127          116   1.000000  0.939655  0.968889  0.987934
2         42       2142          239   0.969388  0.794979  0.873563  0.971677
3         43       1327           24   0.000000  0.000000  0.000000  0.793937
4         44       1578           24   0.142857  0.041667  0.064516  0.799657
5         45       1198            5   0.000000  0.000000  0.000000  0.858676
6         46        711            2   0.500000  0.500000  0.500000  0.973907
7         47        836           22   1.000000  0.045455  0.086957  0.899765
8         48        471           36   0.000000  0.000000  0.000000  0.962133
9         49        476           56   0.666667  0.035714  0.067797  0.943707

LightGBM — simple

   time_step  n_samples  n_positives  precision    recall        f1   roc_auc
0         40       1208          112   0.986486  0.651786  0.784946  0.929362
1         41       1127          116   1.000000  0.922414  0.959641  0.991644
2         42       2142          239   0.984536  0.799163  0.882217  0.974535
3         43       1327           24   0.000000  0.000000  0.000000  0.864511
4         44       1578           24   0.166667  0.041667  0.066667  0.820008
5         45       1198            5   0.000000  0.000000  0.000000  0.885834
6         46        711            2   0.333333  0.500000  0.400000  0.971086
7         47        836           22   1.000000  0.045455  0.086957  0.904400
8         48        471           36   0.666667  0.055556  0.102564  0.965709
9         49        476           56   0.600000  0.053571  0.098361  0.938648

In [17]:
print("Random Forest — simple_balanced")
display(rf_per_ts["simple_balanced"])

print("XGBoost — simple_balanced")
display(xgb_per_ts["simple_balanced"])

print("LightGBM — simple_balanced")
display(lgbm_per_ts["simple_balanced"])

Random Forest — simple_balanced

   time_step  n_samples  n_positives  precision    recall        f1   roc_auc
0         40       1208          112   1.000000  0.598214  0.748603  0.907708
1         41       1127          116   1.000000  0.887931  0.940639  0.981420
2         42       2142          239   0.994382  0.740586  0.848921  0.966694
3         43       1327           24   0.000000  0.000000  0.000000  0.648903
4         44       1578           24   0.166667  0.041667  0.066667  0.834808
5         45       1198            5   0.000000  0.000000  0.000000  0.808131
6         46        711            2   1.000000  0.500000  0.666667  0.977080
7         47        836           22   0.000000  0.000000  0.000000  0.893065
8         48        471           36   0.000000  0.000000  0.000000  0.925415
9         49        476           56   1.000000  0.017857  0.035088  0.931781

XGBoost — simple_balanced

   time_step  n_samples  n_positives  precision    recall        f1   roc_auc
0         40       1208          112   0.950617  0.687500  0.797927  0.939431
1         41       1127          116   0.956522  0.948276  0.952381  0.990586
2         42       2142          239   0.910798  0.811715  0.858407  0.974280
3         43       1327           24   0.000000  0.000000  0.000000  0.805577
4         44       1578           24   0.181818  0.083333  0.114286  0.831993
5         45       1198            5   0.000000  0.000000  0.000000  0.885499
6         46        711            2   0.333333  0.500000  0.400000  0.968265
7         47        836           22   0.428571  0.136364  0.206897  0.903786
8         48        471           36   0.764706  0.361111  0.490566  0.966667
9         49        476           56   0.642857  0.160714  0.257143  0.953316

LightGBM — simple_balanced

   time_step  n_samples  n_positives  precision    recall        f1   roc_auc
0         40       1208          112   0.987013  0.678571  0.804233  0.921085
1         41       1127          116   0.981651  0.922414  0.951111  0.989751
2         42       2142          239   0.950249  0.799163  0.868182  0.972206
3         43       1327           24   0.000000  0.000000  0.000000  0.855014
4         44       1578           24   0.166667  0.041667  0.066667  0.795528
5         45       1198            5   0.000000  0.000000  0.000000  0.888684
6         46        711            2   0.250000  0.500000  0.333333  0.982370
7         47        836           22   0.666667  0.090909  0.160000  0.914954
8         48        471           36   0.928571  0.361111  0.520000  0.968327
9         49        476           56   0.800000  0.214286  0.338028  0.954634

## **Static GNN**

In [18]:
from src.data_loader import _load_transactions_edgelist

print(_load_transactions_edgelist().head())
print(_load_transactions_edgelist().shape)

       txId1      txId2
0  230425980    5530458
1  232022460  232438397
2  230460314  230459870
3  230333930  230595899
4  232013274  232029206
(234355, 2)

In [19]:
from src.data_loader import load_transactions_graph_gcn

simple_gcn = load_transactions_graph_gcn()
simple_gcn

Data(x=[202804, 182], edge_index=[2, 233283], y=[202804], train_mask=[202804], test_mask=[202804], time_steps=[202804])

In [2]:
from src.training import run_gcn_experiments

gcn_agg, gcn_per_ts = run_gcn_experiments()
print("Simple 2 Layer GCN - Agg")
display(gcn_agg)

Simple 2 Layer GCN - Agg

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-transactions-graph,GCN,simple,0.8795 ± 0.055,0.263 ± 0.1284,0.3368 ± 0.1574,0.2413 ± 0.0245,0.7434 ± 0.0483
1,elliptic-transactions-graph,GCN,simple_balanced,0.7629 ± 0.0837,0.145 ± 0.0257,0.5906 ± 0.1357,0.2281 ± 0.0239,0.7726 ± 0.0105

In [4]:
print("Simple 2 Layer GCN — simple")
display(gcn_per_ts[gcn_per_ts["setup"] == "simple"])
print("Simple 2 Layer GCN — simple_balanced")
display(gcn_per_ts[gcn_per_ts["setup"] == "simple_balanced"])

Simple 2 Layer GCN — simple

,time_step,n_samples,n_positives,precision,recall,f1,roc_auc,model,setup,seed
0,40,1208,112,0.251082,0.517857,0.338192,0.730868,GCN,simple,42
1,41,1127,116,0.237374,0.405172,0.299363,0.651800,GCN,simple,42
2,42,2142,239,0.449086,0.719665,0.553055,0.885521,GCN,simple,42
3,43,1327,24,0.006098,0.041667,0.010638,0.698868,GCN,simple,42
4,44,1578,24,0.021739,0.208333,0.039370,0.529387,GCN,simple,42
5,45,1198,5,0.000000,0.000000,0.000000,0.580553,GCN,simple,42
6,46,711,2,0.014286,0.500000,0.027778,0.730959,GCN,simple,42
7,47,836,22,0.010204,0.045455,0.016667,0.514128,GCN,simple,42
8,48,471,36,0.045455,0.027778,0.034483,0.711015,GCN,simple,42
9,49,476,56,0.150000,0.107143,0.125000,0.528040,GCN,simple,42
20,40,1208,112,0.208333,0.401786,0.274390,0.673024,GCN,simple,43
21,41,1127,116,0.186667,0.362069,0.246334,0.546757,GCN,simple,43
22,42,2142,239,0.463542,0.744770,0.571429,0.882669,GCN,simple,43
23,43,1327,24,0.000000,0.000000,0.000000,0.691769,GCN,simple,43
24,44,1578,24,0.016835,0.208333,0.031153,0.477008,GCN,simple,43
25,45,1198,5,0.000000,0.000000,0.000000,0.540821,GCN,simple,43
26,46,711,2,0.015385,0.500000,0.029851,0.724612,GCN,simple,43
27,47,836,22,0.010309,0.045455,0.016807,0.479227,GCN,simple,43
28,48,471,36,0.000000,0.000000,0.000000,0.642656,GCN,simple,43
29,49,476,56,0.125000,0.089286,0.104167,0.498618,GCN,simple,43
40,40,1208,112,0.196581,0.410714,0.265896,0.678905,GCN,simple,44
41,41,1127,116,0.175299,0.379310,0.239782,0.569247,GCN,simple,44
42,42,2142,239,0.422633,0.765690,0.544643,0.879763,GCN,simple,44
43,43,1327,24,0.014286,0.083333,0.024390,0.696118,GCN,simple,44
44,44,1578,24,0.013100,0.250000,0.024896,0.489771,GCN,simple,44
45,45,1198,5,0.000000,0.000000,0.000000,0.533613,GCN,simple,44
46,46,711,2,0.012658,0.500000,0.024691,0.722144,GCN,simple,44
47,47,836,22,0.008929,0.045455,0.014925,0.490340,GCN,simple,44
48,48,471,36,0.047619,0.027778,0.035088,0.674777,GCN,simple,44
49,49,476,56,0.148936,0.125000,0.135922,0.500255,GCN,simple,44
60,40,1208,112,0.634146,0.232143,0.339869,0.793551,GCN,simple,45
61,41,1127,116,0.633333,0.163793,0.260274,0.851061,GCN,simple,45
62,42,2142,239,0.714286,0.313808,0.436047,0.868859,GCN,simple,45
63,43,1327,24,0.000000,0.000000,0.000000,0.727488,GCN,simple,45
64,44,1578,24,0.016949,0.041667,0.024096,0.631837,GCN,simple,45
65,45,1198,5,0.000000,0.000000,0.000000,0.574015,GCN,simple,45
66,46,711,2,0.071429,0.500000,0.125000,0.943583,GCN,simple,45
67,47,836,22,0.000000,0.000000,0.000000,0.660040,GCN,simple,45
68,48,471,36,0.000000,0.000000,0.000000,0.825607,GCN,simple,45
69,49,476,56,0.000000,0.000000,0.000000,0.732738,GCN,simple,45
80,40,1208,112,0.571429,0.178571,0.272109,0.774293,GCN,simple,46
81,41,1127,116,0.545455,0.103448,0.173913,0.781856,GCN,simple,46
82,42,2142,239,0.736842,0.234310,0.355556,0.881475,GCN,simple,46
83,43,1327,24,0.000000,0.000000,0.000000,0.728607,GCN,simple,46
84,44,1578,24,0.025641,0.041667,0.031746,0.644091,GCN,simple,46
85,45,1198,5,0.000000,0.000000,0.000000,0.569824,GCN,simple,46
86,46,711,2,0.000000,0.000000,0.000000,0.593794,GCN,simple,46
87,47,836,22,0.000000,0.000000,0.000000,0.684889,GCN,simple,46
88,48,471,36,0.000000,0.000000,0.000000,0.841762,GCN,simple,46
89,49,476,56,0.000000,0.000000,0.000000,0.717304,GCN,simple,46

Simple 2 Layer GCN — simple_balanced

,time_step,n_samples,n_positives,precision,recall,f1,roc_auc,model,setup,seed
10,40,1208,112,0.193069,0.696429,0.302326,0.779824,GCN,simple_balanced,42
11,41,1127,116,0.203354,0.836207,0.327150,0.776305,GCN,simple_balanced,42
12,42,2142,239,0.320988,0.870293,0.468997,0.879890,GCN,simple_balanced,42
13,43,1327,24,0.032432,0.500000,0.060914,0.727680,GCN,simple_balanced,42
14,44,1578,24,0.021136,0.666667,0.040973,0.600815,GCN,simple_balanced,42
15,45,1198,5,0.005650,0.400000,0.011142,0.626655,GCN,simple_balanced,42
16,46,711,2,0.006897,0.500000,0.013605,0.893512,GCN,simple_balanced,42
17,47,836,22,0.044444,0.454545,0.080972,0.701195,GCN,simple_balanced,42
18,48,471,36,0.242857,0.472222,0.320755,0.832759,GCN,simple_balanced,42
19,49,476,56,0.219048,0.410714,0.285714,0.724022,GCN,simple_balanced,42
30,40,1208,112,0.203488,0.625000,0.307018,0.739654,GCN,simple_balanced,43
31,41,1127,116,0.208202,0.568966,0.304850,0.725187,GCN,simple_balanced,43
32,42,2142,239,0.375954,0.824268,0.516383,0.894785,GCN,simple_balanced,43
33,43,1327,24,0.026403,0.333333,0.048930,0.702513,GCN,simple_balanced,43
34,44,1578,24,0.035928,0.500000,0.067039,0.676802,GCN,simple_balanced,43
35,45,1198,5,0.000000,0.000000,0.000000,0.600503,GCN,simple_balanced,43
36,46,711,2,0.003610,0.500000,0.007168,0.740127,GCN,simple_balanced,43
37,47,836,22,0.023121,0.181818,0.041026,0.597163,GCN,simple_balanced,43
38,48,471,36,0.055556,0.055556,0.055556,0.769317,GCN,simple_balanced,43
39,49,476,56,0.228916,0.339286,0.273381,0.652168,GCN,simple_balanced,43
50,40,1208,112,0.179724,0.696429,0.285714,0.733650,GCN,simple_balanced,44
51,41,1127,116,0.182203,0.741379,0.292517,0.733961,GCN,simple_balanced,44
52,42,2142,239,0.209325,0.882845,0.338412,0.844975,GCN,simple_balanced,44
53,43,1327,24,0.033254,0.583333,0.062921,0.732252,GCN,simple_balanced,44
54,44,1578,24,0.015134,0.541667,0.029445,0.623498,GCN,simple_balanced,44
55,45,1198,5,0.005865,0.400000,0.011561,0.652976,GCN,simple_balanced,44
56,46,711,2,0.006024,0.500000,0.011905,0.764810,GCN,simple_balanced,44
57,47,836,22,0.038462,0.454545,0.070922,0.629048,GCN,simple_balanced,44
58,48,471,36,0.179104,0.333333,0.233010,0.780332,GCN,simple_balanced,44
59,49,476,56,0.267857,0.535714,0.357143,0.696259,GCN,simple_balanced,44
70,40,1208,112,0.279188,0.491071,0.355987,0.793152,GCN,simple_balanced,45
71,41,1127,116,0.254902,0.448276,0.325000,0.766039,GCN,simple_balanced,45
72,42,2142,239,0.409214,0.631799,0.496711,0.866968,GCN,simple_balanced,45
73,43,1327,24,0.030769,0.166667,0.051948,0.730270,GCN,simple_balanced,45
74,44,1578,24,0.017632,0.291667,0.033254,0.546815,GCN,simple_balanced,45
75,45,1198,5,0.000000,0.000000,0.000000,0.575189,GCN,simple_balanced,45
76,46,711,2,0.015873,0.500000,0.030769,0.851904,GCN,simple_balanced,45
77,47,836,22,0.000000,0.000000,0.000000,0.669421,GCN,simple_balanced,45
78,48,471,36,0.080000,0.055556,0.065574,0.820498,GCN,simple_balanced,45
79,49,476,56,0.081633,0.071429,0.076190,0.750595,GCN,simple_balanced,45
90,40,1208,112,0.241546,0.446429,0.313480,0.795572,GCN,simple_balanced,46
91,41,1127,116,0.250000,0.465517,0.325301,0.818923,GCN,simple_balanced,46
92,42,2142,239,0.437653,0.748954,0.552469,0.864831,GCN,simple_balanced,46
93,43,1327,24,0.012195,0.083333,0.021277,0.712842,GCN,simple_balanced,46
94,44,1578,24,0.020942,0.333333,0.039409,0.589902,GCN,simple_balanced,46
95,45,1198,5,0.000000,0.000000,0.000000,0.588768,GCN,simple_balanced,46
96,46,711,2,0.014925,0.500000,0.028986,0.723554,GCN,simple_balanced,46
97,47,836,22,0.021978,0.090909,0.035398,0.636922,GCN,simple_balanced,46
98,48,471,36,0.045455,0.027778,0.034483,0.804278,GCN,simple_balanced,46
99,49,476,56,0.147059,0.089286,0.111111,0.774150,GCN,simple_balanced,46

In [7]:
from src.training import run_graphsage_experiments

sage_agg, sage_per_ts = run_graphsage_experiments()
print("2 Layer graphSAGE - Agg")
display(sage_agg)

2 Layer graphSAGE - Agg

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-transactions-graph,GraphSAGE,simple,0.9571 ± 0.0103,0.673 ± 0.176,0.4179 ± 0.2124,0.4971 ± 0.2381,0.8296 ± 0.0539
1,elliptic-transactions-graph,GraphSAGE,simple_balanced,0.8916 ± 0.0788,0.3703 ± 0.1623,0.606 ± 0.0364,0.4375 ± 0.1294,0.8527 ± 0.0348

In [8]:
print("2 Layer graphSAGE - simple")
display(sage_per_ts[sage_per_ts["setup"] == "simple"])
print("2 Layer graphSAGE - simple_balanced")
display(sage_per_ts[sage_per_ts["setup"] == "simple_balanced"])

2 Layer graphSAGE - simple

,time_step,n_samples,n_positives,precision,recall,f1,roc_auc,model,setup,seed
0,40,1208,112,0.953846,0.553571,0.700565,0.912344,GraphSAGE,simple,42
1,41,1127,116,0.933962,0.853448,0.891892,0.967487,GraphSAGE,simple,42
2,42,2142,239,0.885000,0.740586,0.806378,0.923842,GraphSAGE,simple,42
3,43,1327,24,0.000000,0.000000,0.000000,0.747154,GraphSAGE,simple,42
4,44,1578,24,0.000000,0.000000,0.000000,0.718147,GraphSAGE,simple,42
5,45,1198,5,0.000000,0.000000,0.000000,0.707795,GraphSAGE,simple,42
6,46,711,2,0.000000,0.000000,0.000000,0.401269,GraphSAGE,simple,42
7,47,836,22,0.000000,0.000000,0.000000,0.757259,GraphSAGE,simple,42
8,48,471,36,0.000000,0.000000,0.000000,0.869029,GraphSAGE,simple,42
9,49,476,56,0.000000,0.000000,0.000000,0.774405,GraphSAGE,simple,42
20,40,1208,112,0.792208,0.544643,0.645503,0.832402,GraphSAGE,simple,43
21,41,1127,116,0.910714,0.879310,0.894737,0.956879,GraphSAGE,simple,43
22,42,2142,239,0.774336,0.732218,0.752688,0.939381,GraphSAGE,simple,43
23,43,1327,24,0.000000,0.000000,0.000000,0.663981,GraphSAGE,simple,43
24,44,1578,24,0.000000,0.000000,0.000000,0.527510,GraphSAGE,simple,43
25,45,1198,5,0.000000,0.000000,0.000000,0.653479,GraphSAGE,simple,43
26,46,711,2,0.000000,0.000000,0.000000,0.516925,GraphSAGE,simple,43
27,47,836,22,0.000000,0.000000,0.000000,0.630333,GraphSAGE,simple,43
28,48,471,36,0.000000,0.000000,0.000000,0.889272,GraphSAGE,simple,43
29,49,476,56,0.000000,0.000000,0.000000,0.801871,GraphSAGE,simple,43
40,40,1208,112,0.571429,0.071429,0.126984,0.713960,GraphSAGE,simple,44
41,41,1127,116,0.833333,0.043103,0.081967,0.666935,GraphSAGE,simple,44
42,42,2142,239,0.590909,0.054393,0.099617,0.851472,GraphSAGE,simple,44
43,43,1327,24,0.000000,0.000000,0.000000,0.732029,GraphSAGE,simple,44
44,44,1578,24,0.000000,0.000000,0.000000,0.539039,GraphSAGE,simple,44
45,45,1198,5,0.000000,0.000000,0.000000,0.580218,GraphSAGE,simple,44
46,46,711,2,0.000000,0.000000,0.000000,0.437941,GraphSAGE,simple,44
47,47,836,22,0.000000,0.000000,0.000000,0.563100,GraphSAGE,simple,44
48,48,471,36,0.000000,0.000000,0.000000,0.828544,GraphSAGE,simple,44
49,49,476,56,1.000000,0.017857,0.035088,0.678189,GraphSAGE,simple,44
60,40,1208,112,0.848485,0.500000,0.629213,0.811205,GraphSAGE,simple,45
61,41,1127,116,0.876289,0.732759,0.798122,0.894676,GraphSAGE,simple,45
62,42,2142,239,0.845714,0.619247,0.714976,0.943393,GraphSAGE,simple,45
63,43,1327,24,0.000000,0.000000,0.000000,0.765509,GraphSAGE,simple,45
64,44,1578,24,0.000000,0.000000,0.000000,0.617063,GraphSAGE,simple,45
65,45,1198,5,0.000000,0.000000,0.000000,0.631852,GraphSAGE,simple,45
66,46,711,2,0.000000,0.000000,0.000000,0.526093,GraphSAGE,simple,45
67,47,836,22,0.125000,0.045455,0.066667,0.664843,GraphSAGE,simple,45
68,48,471,36,0.000000,0.000000,0.000000,0.851724,GraphSAGE,simple,45
69,49,476,56,0.000000,0.000000,0.000000,0.738818,GraphSAGE,simple,45
80,40,1208,112,0.701149,0.544643,0.613065,0.831229,GraphSAGE,simple,46
81,41,1127,116,0.878261,0.870690,0.874459,0.952804,GraphSAGE,simple,46
82,42,2142,239,0.590444,0.723849,0.650376,0.916958,GraphSAGE,simple,46
83,43,1327,24,0.000000,0.000000,0.000000,0.746898,GraphSAGE,simple,46
84,44,1578,24,0.000000,0.000000,0.000000,0.505202,GraphSAGE,simple,46
85,45,1198,5,0.000000,0.000000,0.000000,0.665717,GraphSAGE,simple,46
86,46,711,2,0.000000,0.000000,0.000000,0.431594,GraphSAGE,simple,46
87,47,836,22,0.090909,0.045455,0.060606,0.641892,GraphSAGE,simple,46
88,48,471,36,0.000000,0.000000,0.000000,0.836335,GraphSAGE,simple,46
89,49,476,56,0.000000,0.000000,0.000000,0.646344,GraphSAGE,simple,46

2 Layer graphSAGE - simple_balanced

,time_step,n_samples,n_positives,precision,recall,f1,roc_auc,model,setup,seed
10,40,1208,112,0.655462,0.696429,0.675325,0.903048,GraphSAGE,simple_balanced,42
11,41,1127,116,0.741007,0.887931,0.807843,0.958653,GraphSAGE,simple_balanced,42
12,42,2142,239,0.738636,0.815900,0.775348,0.946792,GraphSAGE,simple_balanced,42
13,43,1327,24,0.040000,0.041667,0.040816,0.753741,GraphSAGE,simple_balanced,42
14,44,1578,24,0.000000,0.000000,0.000000,0.736728,GraphSAGE,simple_balanced,42
15,45,1198,5,0.000000,0.000000,0.000000,0.697066,GraphSAGE,simple_balanced,42
16,46,711,2,0.000000,0.000000,0.000000,0.601551,GraphSAGE,simple_balanced,42
17,47,836,22,0.052632,0.045455,0.048780,0.732354,GraphSAGE,simple_balanced,42
18,48,471,36,0.250000,0.027778,0.050000,0.863921,GraphSAGE,simple_balanced,42
19,49,476,56,0.125000,0.017857,0.031250,0.772279,GraphSAGE,simple_balanced,42
30,40,1208,112,0.669725,0.651786,0.660633,0.894381,GraphSAGE,simple_balanced,43
31,41,1127,116,0.740741,0.862069,0.796813,0.948400,GraphSAGE,simple_balanced,43
32,42,2142,239,0.748971,0.761506,0.755187,0.907044,GraphSAGE,simple_balanced,43
33,43,1327,24,0.000000,0.000000,0.000000,0.730494,GraphSAGE,simple_balanced,43
34,44,1578,24,0.013333,0.041667,0.020202,0.578480,GraphSAGE,simple_balanced,43
35,45,1198,5,0.000000,0.000000,0.000000,0.694049,GraphSAGE,simple_balanced,43
36,46,711,2,0.000000,0.000000,0.000000,0.473907,GraphSAGE,simple_balanced,43
37,47,836,22,0.000000,0.000000,0.000000,0.742741,GraphSAGE,simple_balanced,43
38,48,471,36,0.000000,0.000000,0.000000,0.879821,GraphSAGE,simple_balanced,43
39,49,476,56,0.166667,0.017857,0.032258,0.802806,GraphSAGE,simple_balanced,43
50,40,1208,112,0.250000,0.705357,0.369159,0.801282,GraphSAGE,simple_balanced,44
51,41,1127,116,0.237968,0.767241,0.363265,0.793206,GraphSAGE,simple_balanced,44
52,42,2142,239,0.365352,0.891213,0.518248,0.882177,GraphSAGE,simple_balanced,44
53,43,1327,24,0.046512,0.500000,0.085106,0.773519,GraphSAGE,simple_balanced,44
54,44,1578,24,0.016667,0.416667,0.032051,0.595734,GraphSAGE,simple_balanced,44
55,45,1198,5,0.008097,0.400000,0.015873,0.704443,GraphSAGE,simple_balanced,44
56,46,711,2,0.000000,0.000000,0.000000,0.426657,GraphSAGE,simple_balanced,44
57,47,836,22,0.063584,0.500000,0.112821,0.755249,GraphSAGE,simple_balanced,44
58,48,471,36,0.028571,0.027778,0.028169,0.845530,GraphSAGE,simple_balanced,44
59,49,476,56,0.066667,0.071429,0.068966,0.746471,GraphSAGE,simple_balanced,44
70,40,1208,112,0.509934,0.687500,0.585551,0.899236,GraphSAGE,simple_balanced,45
71,41,1127,116,0.537572,0.801724,0.643599,0.926357,GraphSAGE,simple_balanced,45
72,42,2142,239,0.587879,0.811715,0.681898,0.932835,GraphSAGE,simple_balanced,45
73,43,1327,24,0.056075,0.250000,0.091603,0.764582,GraphSAGE,simple_balanced,45
74,44,1578,24,0.016461,0.166667,0.029963,0.641248,GraphSAGE,simple_balanced,45
75,45,1198,5,0.000000,0.000000,0.000000,0.678961,GraphSAGE,simple_balanced,45
76,46,711,2,0.000000,0.000000,0.000000,0.711566,GraphSAGE,simple_balanced,45
77,47,836,22,0.075000,0.136364,0.096774,0.768707,GraphSAGE,simple_balanced,45
78,48,471,36,0.142857,0.027778,0.046512,0.864432,GraphSAGE,simple_balanced,45
79,49,476,56,0.105263,0.035714,0.053333,0.754549,GraphSAGE,simple_balanced,45
90,40,1208,112,0.506250,0.723214,0.595588,0.897818,GraphSAGE,simple_balanced,46
91,41,1127,116,0.587209,0.870690,0.701389,0.955618,GraphSAGE,simple_balanced,46
92,42,2142,239,0.540984,0.828452,0.654545,0.935183,GraphSAGE,simple_balanced,46
93,43,1327,24,0.016667,0.041667,0.023810,0.745491,GraphSAGE,simple_balanced,46
94,44,1578,24,0.024845,0.166667,0.043243,0.621273,GraphSAGE,simple_balanced,46
95,45,1198,5,0.000000,0.000000,0.000000,0.688516,GraphSAGE,simple_balanced,46
96,46,711,2,0.000000,0.000000,0.000000,0.460508,GraphSAGE,simple_balanced,46
97,47,836,22,0.021277,0.045455,0.028986,0.719623,GraphSAGE,simple_balanced,46
98,48,471,36,0.076923,0.027778,0.040816,0.852043,GraphSAGE,simple_balanced,46
99,49,476,56,0.090909,0.035714,0.051282,0.786097,GraphSAGE,simple_balanced,46

## **DynamicGNN**:
---

In [2]:
from src.training import run_evolve_gcn_experiments

evolve_summary, evolve_per_ts = run_evolve_gcn_experiments()
print("EvolveGCN - Agg")
display(evolve_summary)
print("EvolveGCN - simple")
display(evolve_per_ts[evolve_per_ts["setup"] == "simple"])
#print("EvolveGCN - simple_balanced")
#display(evolve_per_ts[evolve_per_ts["setup"] == "simple_balanced"])

EvolveGCN - Agg

,dataset,model,setup,accuracy,precision,recall,f1,roc_auc
0,elliptic-transactions-graph,EvolveGCN-O,simple,NaN,NaN,NaN,NaN,NaN

EvolveGCN - simple

,time_step,n_samples,n_positives,precision,recall,f1,roc_auc,model,setup,seed
0,17,811,99,0.0,0.0,0.0,0.769280,EvolveGCN-O,simple,42
1,18,388,52,0.0,0.0,0.0,0.700864,EvolveGCN-O,simple,42
2,19,745,80,0.0,0.0,0.0,0.550150,EvolveGCN-O,simple,42
3,20,897,260,0.0,0.0,0.0,0.642320,EvolveGCN-O,simple,42
4,21,640,100,0.0,0.0,0.0,0.626722,EvolveGCN-O,simple,42
5,22,1754,158,0.0,0.0,0.0,0.642572,EvolveGCN-O,simple,42
6,23,1157,53,0.0,0.0,0.0,0.617155,EvolveGCN-O,simple,42
7,24,1122,137,0.0,0.0,0.0,0.534640,EvolveGCN-O,simple,42
8,25,594,118,0.0,0.0,0.0,0.529180,EvolveGCN-O,simple,42
9,26,517,96,0.0,0.0,0.0,0.641701,EvolveGCN-O,simple,42
10,27,196,24,0.0,0.0,0.0,0.670058,EvolveGCN-O,simple,42
11,28,284,85,0.0,0.0,0.0,0.494945,EvolveGCN-O,simple,42
12,29,1172,329,0.0,0.0,0.0,0.545652,EvolveGCN-O,simple,42
13,30,523,83,0.0,0.0,0.0,0.694660,EvolveGCN-O,simple,42
14,31,682,106,0.0,0.0,0.0,0.603004,EvolveGCN-O,simple,42
15,32,1312,342,0.0,0.0,0.0,0.585000,EvolveGCN-O,simple,42
16,33,441,23,0.0,0.0,0.0,0.538278,EvolveGCN-O,simple,42
17,34,514,37,0.0,0.0,0.0,0.631792,EvolveGCN-O,simple,42
18,35,1332,182,0.0,0.0,0.0,0.738899,EvolveGCN-O,simple,42
19,36,1596,33,0.0,0.0,0.0,0.923961,EvolveGCN-O,simple,42
20,37,446,40,0.0,0.0,0.0,0.643658,EvolveGCN-O,simple,42
21,38,747,111,0.0,0.0,0.0,0.721337,EvolveGCN-O,simple,42
22,39,1151,81,0.0,0.0,0.0,0.729457,EvolveGCN-O,simple,42
23,40,1208,112,0.0,0.0,0.0,0.624723,EvolveGCN-O,simple,42
24,41,1127,116,0.0,0.0,0.0,0.830370,EvolveGCN-O,simple,42
25,42,2142,239,0.0,0.0,0.0,0.631234,EvolveGCN-O,simple,42
26,43,1327,24,0.0,0.0,0.0,0.497698,EvolveGCN-O,simple,42
27,44,1578,24,0.0,0.0,0.0,0.493565,EvolveGCN-O,simple,42
28,45,1198,5,0.0,0.0,0.0,0.497485,EvolveGCN-O,simple,42
29,46,711,2,0.0,0.0,0.0,0.499295,EvolveGCN-O,simple,42
30,47,836,22,0.0,0.0,0.0,0.490172,EvolveGCN-O,simple,42
31,48,471,36,0.0,0.0,0.0,0.495402,EvolveGCN-O,simple,42
32,49,476,56,0.0,0.0,0.0,0.500000,EvolveGCN-O,simple,42